package com.dianziqueen.app

/** 编译期显式引用 raw 资源，供 Lint 与 R8 识别。 */
object QueenRawAssets {

    val wallpaperIds: IntArray = intArrayOf(
        R.raw.wallpaper_1,
        R.raw.wallpaper_2,
        R.raw.wallpaper_3,
        R.raw.wallpaper_4,
        R.raw.wallpaper_5,
        R.raw.wallpaper_6,
        R.raw.wallpaper_7,
        R.raw.wallpaper_8,
        R.raw.wallpaper_9,
        R.raw.wallpaper_10,
        R.raw.wallpaper_11,
        R.raw.wallpaper_12,
        R.raw.wallpaper_13,
        R.raw.wallpaper_14,
        R.raw.wallpaper_15,
        R.raw.wallpaper_16,
        R.raw.wallpaper_17,
        R.raw.wallpaper_18,
        R.raw.wallpaper_19,
        R.raw.wallpaper_20,
        R.raw.wallpaper_21,
        R.raw.wallpaper_22,
        R.raw.wallpaper_23,
        R.raw.wallpaper_24,
        R.raw.wallpaper_25,
        R.raw.wallpaper_26,
        R.raw.wallpaper_27,
        R.raw.wallpaper_28,
        R.raw.wallpaper_29,
        R.raw.wallpaper_30,
        R.raw.wallpaper_31,
        R.raw.wallpaper_32,
        R.raw.wallpaper_33,
        R.raw.wallpaper_34,
        R.raw.wallpaper_35,
        R.raw.wallpaper_36,
        R.raw.wallpaper_37,
        R.raw.wallpaper_38,
        R.raw.wallpaper_39,
        R.raw.wallpaper_40,
        R.raw.wallpaper_41,
        R.raw.wallpaper_42,
    )
}
